// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BillingToggleController from "./billing_toggle_controller"
application.register("billing-toggle", BillingToggleController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvoiceFormController from "./invoice_form_controller"
application.register("invoice-form", InvoiceFormController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import ScrollAnimatorController from "./scroll_animator_controller"
application.register("scroll-animator", ScrollAnimatorController)

import ScrollToBottomController from "./scroll_to_bottom_controller"
application.register("scroll-to-bottom", ScrollToBottomController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TypewriterController from "./typewriter_controller"
application.register("typewriter", TypewriterController)
